INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('NP5', 'P5', '2D');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('NP6', 'P6', '2D');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('NC1', 'C1', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('NC2', 'C2', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('NC3', 'C3', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('NW1', 'W1', '1K');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('NW2', 'W2', '1K');

INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('RAM', 'ROY', '000ramroy@google.com', 'IN', '2872 Marquette Street', 'MP', '91-(100)100-0013');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('AHANA', 'SINGH', '000ahanasingh@google.com', 'IN', '3538 Scofield Drive', 'UP', '91-(100)100-0005');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('RAKESH', 'SONI', '000rakeshsoni@google.com', 'IN', '805 Paget Court', 'CG', '91-(100)100-0009');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('ANSH', 'KUMAR', '000anshkumar@google.com', 'IN', '4514 Independence Point', 'MP', '91-(100)100-0017');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('ROHAN', 'A', '000rohana@google.com', 'IN', '21 Sauthoff Point', 'UP', '91-(100)100-0003');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('KARAN', 'SINGH', '000karansharma@google.com', 'IN', '9857 Hollow Ridge Park', 'MH', '91-(100)100-0007');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('VIKRAM', 'SINHA', '000vikramsinha@google.com', 'IN', '8 Crescent Oaks Circle', 'MP', '91-(100)100-0019');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('NARAYAN', 'SINGH', '000narayansingh@google.com', 'IN', '02 Haas Park', 'MH', '91-(100)100-0004');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('HARSH', 'SINGH', '000harshsingh@google.com', 'IN', '4903 Commercial Drive', 'MH', '91-(100)100-0029');
INSERT INTO GUEST (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('PIYUSH', 'SHARMA', '000piyushsharma@google.com', 'IN', '1208 Menomonie Terrace', 'CG', '91-(100)100-0001');


INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'C2'), (SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'SHARMA'), '2020-01-01');

